

export const Movies=[
    {id:Math.random(),
        Name:"Red Notice",
        Rating: 5 ,
         Date: "novembre 2021" ,
         image: "https://fr.web.img6.acsta.net/pictures/21/10/21/15/41/2023058.jpg",
         desc:"Red Notice is a 2021 American action comedy film written, directed, and produced by Rawson Marshall Thurber. Dwayne Johnson, who also served as a producer, stars as an FBI agent who reluctantly teams up with a renowned art thief (Ryan Reynolds) in order to catch an even more notorious criminal (Gal Gadot). ",
         trailer:"https://www.youtube.com/embed/Pj0wz7zu3Ms"},
    {id:Math.random(),
        Name:"Parasite",
        Rating: 4 ,
         Date: "mai 2019" ,
         image: "https://media.senscritique.com/media/000018573383/source_big/Parasite.jpg",
         desc:"est un film sud-coréen coécrit et réalisé par Bong Joon-ho, sorti en 2019. Le film est présenté en compétition officielle au Festival de Cannes 2019, où il remporte la Palme d'or à l'unanimité du jury. Il est le premier film sud-coréen à obtenir cette récompense",
         trailer:"https://www.youtube.com/embed/SEUXfv87Wpk"},
    {id:Math.random(),
        Name:"Paper Lives",
        Rating: 3 ,
         Date: "mars 2021" ,
         image: "https://s.3isk.video/wp-content/uploads/2021/03/cmru6N6Hnw2pJwuo1ctH1CxKqKZ.jpg",
         desc:"is a 2021 Turkish drama film directed by Can Ulkay and written by Ercan Mehmet Erdem. The film stars Çağatay Ulusoy, Emir Ali Doğrul, Ersin Arc, Turgay Tanülkü and Selen Öztürk. It premiered on Netflix on March 12, 2021.",
         trailer:"https://www.youtube.com/embed/lXdSaVK-vzs"},
    {id:Math.random(),
        Name:"La Plateforme",
        Rating: 5 , 
        Date: "novembre 2019" ,
        image: "https://fr.web.img6.acsta.net/pictures/19/09/02/16/57/3762755.jpg",
        desc:" est un film espagnol réalisé par Galder Gaztelu-Urrutia, sorti en 2019",
        trailer:"https://www.youtube.com/embed/RlfooqeZcdY"},
    {id:Math.random(),
        Name:"Tyler Rake",
        Rating: 2 , 
        Date: "avril 2020" ,
        image: "https://fr.web.img6.acsta.net/pictures/20/03/31/09/22/0259222.jpg",
        desc:"est un film d'action américain réalisé par Sam Hargrave, sorti en 2020 sur Netflix. Il s’agit de l’adaptation du comic book intitulé Ciudad d’Ande Parks, Joe Russo, Anthony Russo, Fernando Leon Gonzalez et Eric Skillman",
        trailer:"https://www.youtube.com/embed/usvcFcnz2rs"},
       , 
]
